# Generated by Django 4.1.4 on 2022-12-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_urls_created_at_urls_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Shortener',
        ),
    ]
