# Generated by Django 4.1.4 on 2022-12-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_rename_urls_shortener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
