name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  push_dockers:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        run: |
          ls
          cd backend
          docker build . --tag titanmen/bit2.one_backend:latest
          docker push titanmen/bit2.one_backend:latest 

      - name: Build and push Nginx Docker image
        run: |
          ls
          cd deploy/nginx
          docker build . --tag titanmen/bit2.one_nginx:latest
          docker push titanmen/bit2.one_nginx:latest 

  deploy:
    needs: [lint, push_dockers]
    runs-on: ubuntu-latest

    steps:
      - name: ReUp dockers to VPS via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            ls
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/for_github_pulling
            cd bit2.one
            git pull
            cd deploy
            docker compose stop
            docker compose up -d

  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install poetry
          cd backend
          make package-install
      - name: Lint
        run: |
          cd backend
          make lint
